version: '3.8'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - "4040:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions

  db:
    build: .
    container_name: Members
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Members
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  app:
    image: myapp
    container_name: Myapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-tutorial-database.cm7j3stjsd9t.ap-northeast-1.rds.amazonaws.com:3306/my-tutorial-database
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: aaaaaaa
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.jdbc.Driver
